# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libraryInventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16libraryInventory.proto\x12\x07library\"w\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x13\n\x0bpublishyear\x18\x04 \x01(\x05\x12-\n\x05genre\x18\x05 \x01(\x0e\x32\x12.library.GenreType:\nNONFICTION\"\x85\x01\n\rInventoryItem\x12\x17\n\x0finventoryNumber\x18\x01 \x01(\t\x12\x1d\n\x04\x62ook\x18\x02 \x01(\x0b\x32\r.library.BookH\x00\x12.\n\x06status\x18\x03 \x01(\x0e\x32\x13.library.StatusType:\tAVAILABLEB\x0c\n\nbook_oneof\"x\n\x11\x43reateBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x13\n\x0bpublishyear\x18\x04 \x01(\x05\x12!\n\x05genre\x18\x05 \x01(\x0e\x32\x12.library.GenreType\"%\n\x12\x43reateBookResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"?\n\x0fGetBookResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1b\n\x04\x62ook\x18\x02 \x01(\x0b\x32\r.library.Book*@\n\tGenreType\x12\x0b\n\x07\x46\x41NTASY\x10\x00\x12\t\n\x05NOVEL\x10\x01\x12\x0e\n\nNONFICTION\x10\x02\x12\x0b\n\x07\x46ICTION\x10\x03*&\n\nStatusType\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x32\x9b\x01\n\x10InventoryService\x12G\n\nCreateBook\x12\x1a.library.CreateBookRequest\x1a\x1b.library.CreateBookResponse\"\x00\x12>\n\x07GetBook\x12\x17.library.GetBookRequest\x1a\x18.library.GetBookResponse\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libraryInventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRETYPE._serialized_start=550
  _GENRETYPE._serialized_end=614
  _STATUSTYPE._serialized_start=616
  _STATUSTYPE._serialized_end=654
  _BOOK._serialized_start=35
  _BOOK._serialized_end=154
  _INVENTORYITEM._serialized_start=157
  _INVENTORYITEM._serialized_end=290
  _CREATEBOOKREQUEST._serialized_start=292
  _CREATEBOOKREQUEST._serialized_end=412
  _CREATEBOOKRESPONSE._serialized_start=414
  _CREATEBOOKRESPONSE._serialized_end=451
  _GETBOOKREQUEST._serialized_start=453
  _GETBOOKREQUEST._serialized_end=483
  _GETBOOKRESPONSE._serialized_start=485
  _GETBOOKRESPONSE._serialized_end=548
  _INVENTORYSERVICE._serialized_start=657
  _INVENTORYSERVICE._serialized_end=812
# @@protoc_insertion_point(module_scope)
